version: '3.3'

services:
  db:
    image: postgres:9.4.18-alpine
    environment:
    - POSTGRES_DB=test
    - POSTGRES_USER=test
    - POSTGRES_PASSWORD=test
    ports:
    - 5432:5432
    volumes:
    - db_data:/var/lib/postgresql/data

volumes:
  db_data: 