spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
---
spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost/test
    username: test
    password: test
---
spring:
  profiles: ci
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://postgres/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}